### ISSUE TITLE
remove hardcoded default for auxConfPath

### ISSUE THREAD

**Issue by balmas** [alpheios-project/arethusa#661]
we should not have any urls hardcoded in javascript:

https://github.com/latin-language-toolkit/arethusa/blob/master/app/js/arethusa.core/configurator.js#L108

**Comment by LFDM** [comment]
Totally agree in general - but now that we release these auxiliary things in `arethusa-configs`, we could just link to github as a fallback, which should be fairly stable. (wasn't possible before, because the `dist` folder there was not under git control)

Something like `http://raw.githubusercontent.com/latin-language-toolkit/arethusa-configs/master/dist`

What do you think?

**Comment by balmas** [comment]
yes, I guess that's okay too. Although I haven't been regularly updating dist...

**Comment by LFDM** [comment]
I think that's ok - it would be a fallback - and we declare the path to perseids in the perseids conf files explicitly.
