### ISSUE TITLE
duplicate morphology data?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/arethusa#674]
reported by @vgorman1

Another thing I notice about morphologies is that, as soon as I label or confirm a label  (I do not even need to change it, but just save the sentence), every morphology is labeled “document” and they are very often duplicated with another label “bsp/morphologies”.  So, the minute I open a sentence with Preselect on, and I save the sentence without touching anything, when I come back to it every single morphology is labeled “document”. I do not think it has been doing this all along, and I have no idea if this is a problem.

**Comment by balmas** [comment]
@vgorman1 I'm not sure this is really a problem, and am guessing this is a result of the changes in #639 to store morphology preferences and/or in the fix tto add the unused token counter to the morphology tab (fdaa2cd5475d273612d0e32e943de17c0ac755c9). The cache of what the browser new about the morphology between reloads of a document is more current, and I the behavior you are seeing as far the label is concerned is technically correct, because as soon as you save with morphology data selected (or preselected as the case may be), the selected form is technically "in the document" 

I'm not so sure about the duplicates with the bsp/morpheus data though... these should be deduped out and I am having trouble reproducing that.

**Comment by balmas** [comment]
@Masoumeh Something we should look into here: I note that `morph.mergeDuplicateForms` explicitly only dedupes the automated analyses with forms that came from the original document (by looking at `origin === 'document'`), which could explain weird behavior around duplicates when a cached form supplied by the user is also present. This might be intentional or it might be holdover code that was never updated when the `you` source for local storage was added.

**Comment by Masoumeh** [comment]
Hi @balmas, 
there is a point that we should consider and I am not sure how to deal with it.
If a form is **selected**, the retriever reads it separately as an analysis object. Since this object does not have an origin, the origin is set to "document".
On the other hand, we have this same data also from the local storage or other services (like bsp).
So, although the merging process is probably done correctly, the pushAll function will add
the merged one to the forms array which already contains the analysis object. It means that we would have duplicate data. The question is if there is any reason for that? Should we rewrite the code such that the form, which is going into the process of merging, should also be removed from the variable **forms**.

The other problem regarding the origin of 'you' or 'document' can probably be solved as below in the function **mergeDuplicateForms**:
if(duplicate.origin == "you") firstForm.origin="you";
else firstForm.origin = 'document';

What do you think?

**Comment by balmas** [comment]
@Masoumeh can you clarify which point in the code you're talking about with the form being selected? Is it these lines in getAnalysisFromState?
https://github.com/alpheios-project/arethusa/blob/master/app/js/arethusa.morph/morph.js#L244-L245

As for the 2nd question, maybe what we really need  to do is produce a set of state diagrams that document all the possible ways the morph.analysis gets updated, starting from the load of a new document into the system, and taking into account the interactions with the bsp service, the local cache and user actions. Basically taking the natural language document I produced at https://github.com/alpheios-project/arethusa/wiki/Morphology-Handling and turning into a diagram or set of diagrams that let us see more clearly what is happening and where things can go wrong.

What do you think? Would you be willing to try that?

**Comment by balmas** [comment]
see #707
