### ISSUE TITLE
Path incorrect for Foundation scss imports

### ISSUE THREAD

**Issue by fbaumgardt** [alpheios-project/arethusa#725]
The relative paths for the imports in [_foundation.scss on the master](https://github.com/alpheios-project/arethusa/blob/d7069dd24c5ea5070abc84657b1994905386a285/app/css/_foundation.scss) branch are incorrect. I'm new to Grunt, is this an issue on my system/conf only, am I possibly forgetting to run another task first, or does this need fixing?

**Comment by balmas** [comment]
It appears the sass gem used by the grunt sass task automatically adds the current working directory the list of loadPaths it checks for imports.  So since the grunt tasks is run from the base dir, it parses the paths in the _foundation.css in the context of the root working directory, as well as relative to arethusa/app/css at the root, as well as relative to the file that import.

This is apparently deprecated functionality though (see https://github.com/sass/sass/blob/4ef8e3167985ace91b2105916756bd93c5d7bba6/lib/sass/importers/deprecated_path.rb) -- and we should be explicit about it by setting the load paths in the Gruntfile config for the sass tasks.

**Comment by fbaumgardt** [comment]
Excellent find! I am indeed using sass v3.4+

**Comment by fbaumgardt** [comment]
PS: Feel free to ignore the PR if you'd rather fix it in the Gruntfile.

**Comment by balmas** [comment]
changing the paths in the files is fine with me too

**Comment by fbaumgardt** [comment]
Sorry, I will have to revisit this and fix it in the config files, because while this removed the error message and let me finish the build, the compiled CSS doesn't get merged into the minified CSS. Not a big thing, I was going to review the Gruntfile next anyways.

**Comment by balmas** [comment]
it could be that we could get away from using a custom foundation css built into the arethusa.css now anyway. See this lovely little cryptic issue: #463

**Comment by fbaumgardt** [comment]
Thanks for the pointer! I combed through the commit log and didn't find any explanation with specific regards to the CSS, only a patch in the JS. Do you know any more about it?

**Comment by balmas** [comment]
sadly no.  My approach would probably be to compare the css with the official version and then search in the code for usage of the classes that differ.
