### ISSUE TITLE
ability to expand/collapse branches

### ISSUE THREAD

**Issue by balmas** [alpheios-project/arethusa#824]
requested by @vgorman1

...helpful for pedagogy ..if we could close down branches of the tree as we used to do way back when.  Remember when you could click on a word, and the entirety of the tree elements dependent upon it would close up like a drop-down menu?  The benefits are twofold: 1) when you are working on huge sentences, there is very little box left in which to make the tree and you cannot see what you are doing; and 2) one could easily simplify a longer tree when presenting it to students so that you look at it one clause at a time.

**Comment by balmas** [comment]
@zfletch same question as for #825  - will this be supported in the react viewer?

**Comment by zfletch** [comment]
@balmas am I understanding correctly that this issue is for expanding and collapsing subtrees and https://github.com/alpheios-project/arethusa/issues/825 is about configuring the viewer to have certain subtrees expanded or collapsed on page load?

If that is the case, then I think that this issue would be addressed in https://github.com/perseids-tools/treebank-react/issues/21 and https://github.com/alpheios-project/arethusa/issues/825 would actually be addressed in https://github.com/perseids-tools/treebank-react/issues/8.

**Comment by balmas** [comment]
> @balmas am I understanding correctly that this issue is for expanding and collapsing subtrees and #825 is about configuring the viewer to have certain subtrees expanded or collapsed on page load?
> 

@zfletch  Yes that's correct. Thanks!

**Comment by balmas** [comment]
closing this. it will be fixed in the new viewer app.
